#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_artist_index:
   path: /artists
   controller: App\Controller\ArtistController::index

app_api_artist:
   path: /api/artists
   controller: App\Controller\API\ApiArtistController::index

