#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
   path: /
   controller: App\Controller\HomeController::index

app_artist_index:
   path: /artists
   controller: App\Controller\ArtistController::index

app_date_index:
   path: /date
   controller: App\Controller\DateController::index

app_ticket:
   path: /ticket
   controller: App\Controller\TicketController::index



# API routes -----------------------------------------------

app_api_artist:
   path: /api/artists
   controller: App\Controller\API\ApiArtistController::index

app_api_picture_id:
   path: /api/pictures/{id}
   controller: App\Controller\API\ApiPictureController::index

app_api_artist_isformer:
   path : /api/artists/is_former
   controller: App\Controller\API\ApiArtistController::getFormerArtists

app_api_plays:
   path: /api/plays
   controller: App\Controller\API\ApiPlayController::index

app_api_play_name: 
   path: /api/play/{name}
   controller: App\Controller\API\ApiPlayController::getByName

app_api_date:
   path: /api/date
   controller: App\Controller\API\ApiDateController::index

app_api_subscribers_list:
   path: /api/subscribers
   controller: App\Controller\API\ApiNewsletterController::index

app_api_subscribe:
   path: /api/newsletter/subscribe
   controller: App\Controller\API\ApiNewsletterController::subscribe
   methods: POST

app_api_unsubscribe:
   path: /api/newsletter/unsubscribe/{id}
   controller: App\Controller\API\ApiNewsletterController::unsubscribe
   methods: DELETE

app_api_newsletter_getid:
   path: /api/newsletter/get_id
   controller: App\Controller\API\ApiNewsletterController::getId
   methods: POST


app_api_email_subscription:
   path: /api/subscription-confirmation
   controller: App\Controller\MailerController::sendEmail

app_api_ticket_create:
   path: /api/ticket/create
   controller: App\Controller\API\ApiTicketController::createTicket
   methods: POST

